spring.application.name=donut

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# MySQL 연결 정보
spring.datasource.url=jdbc:mysql://localhost:3306/donut
spring.datasource.username=donut
spring.datasource.password=mithon!donut
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect